"""Shared utilities and constants.

共享工具类和常量，被多层共享使用。
"""

from .constants import (
    AVATAR_CACHE_MAX_SIZE,
    AVATAR_CACHE_TTL,
    CALENDAR_IMAGE_WIDTH,
    CHARACTER_RANGE_HIGH,
    CHARACTER_RANGE_LOW,
    CHARACTER_RANGE_MEDIUM,
    CHARACTER_THRESHOLD_HIGH,
    CHARACTER_THRESHOLD_MEDIUM,
    DEFAULT_COUNT_DISPLAY_MODE,
    DEFAULT_DAILY_RETRO_LIMIT,
    DEFAULT_SHOW_CHECK_MARK,
    HTTP_TIMEOUT_SECONDS,
    IMPORT_SESSION_TIMEOUT,
    LLM_TOOL_DEER_OTHER,
    LLM_TOOL_DEER_SELF,
    LLM_TOOL_GET_USER_DEER_DATA,
    LLM_TOOL_RETRO_DEER,
    LLM_TOOL_SET_ALLOW_HELP,
    LLM_TOOLS,
    MAX_FONT_SIZE,
    MAX_IMPORT_FILE_SIZE,
    PLATFORM_AIOCQHTTP,
    QQ_AVATAR_URL_TEMPLATE,
    TEMPLATE_CALENDAR_LOAD_FAILED,
    TEMPLATE_DEER_PAST_LIMIT,
    TEMPLATE_DEER_PAST_SUCCESS,
    TEMPLATE_FALLBACK_CALENDAR_HEADER,
    TEMPLATE_FALLBACK_CALENDAR_STATS,
    TEMPLATE_GROUP_ONLY,
    TEMPLATE_OPERATION_FAILED,
)

__all__ = [
    "AVATAR_CACHE_MAX_SIZE",
    "AVATAR_CACHE_TTL",
    "CALENDAR_IMAGE_WIDTH",
    "CHARACTER_RANGE_HIGH",
    "CHARACTER_RANGE_LOW",
    "CHARACTER_RANGE_MEDIUM",
    "CHARACTER_THRESHOLD_HIGH",
    "CHARACTER_THRESHOLD_MEDIUM",
    "DEFAULT_COUNT_DISPLAY_MODE",
    "DEFAULT_DAILY_RETRO_LIMIT",
    "DEFAULT_SHOW_CHECK_MARK",
    "HTTP_TIMEOUT_SECONDS",
    "IMPORT_SESSION_TIMEOUT",
    "LLM_TOOLS",
    "LLM_TOOL_DEER_OTHER",
    "LLM_TOOL_DEER_SELF",
    "LLM_TOOL_GET_USER_DEER_DATA",
    "LLM_TOOL_RETRO_DEER",
    "LLM_TOOL_SET_ALLOW_HELP",
    "MAX_FONT_SIZE",
    "MAX_IMPORT_FILE_SIZE",
    "PLATFORM_AIOCQHTTP",
    "QQ_AVATAR_URL_TEMPLATE",
    "TEMPLATE_CALENDAR_LOAD_FAILED",
    "TEMPLATE_DEER_PAST_LIMIT",
    "TEMPLATE_DEER_PAST_SUCCESS",
    "TEMPLATE_FALLBACK_CALENDAR_HEADER",
    "TEMPLATE_FALLBACK_CALENDAR_STATS",
    "TEMPLATE_GROUP_ONLY",
    "TEMPLATE_OPERATION_FAILED",
]

from .paths import ResourcePaths

__all__.append("ResourcePaths")
